csslist = 'ul.class_3_2:nth-child(1) > li:nth-child(2),ul.class_3_2:nth-child(3) > li:nth-child(2),ul.class_3_2:nth-child(5) > li:nth-child(2),ul.class_3_2:nth-child(7) > li:nth-child(2),ul.class_3_2:nth-child(9) > li:nth-child(2),ul.class_3_2:nth-child(11) > li:nth-child(2),ul.class_3_2:nth-child(13) > li:nth-child(2),ul.class_3_2:nth-child(15) > li:nth-child(2)'
clicks = '#ctl00_ContentPlaceHolder1_rptStudy_ctl00_aButton,#ctl00_ContentPlaceHolder1_rptStudy_ctl02_aButton,#ctl00_ContentPlaceHolder1_rptStudy_ctl04_aButton,#ctl00_ContentPlaceHolder1_rptStudy_ctl06_aButton,#ctl00_ContentPlaceHolder1_rptStudy_ctl08_aButton,#ctl00_ContentPlaceHolder1_rptStudy_ctl10_aButton,#ctl00_ContentPlaceHolder1_rptStudy_ctl12_aButton,#ctl00_ContentPlaceHolder1_rptStudy_ctl14_aButton'
csslist2 = 'ul.class_3_2:nth-child(1) > li:nth-child(2),ul.class_3_2:nth-child(3) > li:nth-child(2),ul.class_3_2:nth-child(5) > li:nth-child(2),ul.class_3_2:nth-child(7) > li:nth-child(2),ul.class_3_2:nth-child(9) > li:nth-child(2),ul.class_3_2:nth-child(11) > li:nth-child(2),ul.class_3_2:nth-child(13) > li:nth-child(2),ul.class_3_2:nth-child(15) > li:nth-child(2),ul.class_3_2:nth-child(17) > li:nth-child(2),ul.class_3_2:nth-child(19) > li:nth-child(2),ul.class_3_2:nth-child(21) > li:nth-child(2),ul.class_3_2:nth-child(23) > li:nth-child(2),ul.class_3_2:nth-child(25) > li:nth-child(2),ul.class_3_2:nth-child(27) > li:nth-child(2)'
clicks2 = '#ctl00_ContentPlaceHolder1_rptStudy_ctl00_aButton,#ctl00_ContentPlaceHolder1_rptStudy_ctl02_aButton,#ctl00_ContentPlaceHolder1_rptStudy_ctl04_aButton,#ctl00_ContentPlaceHolder1_rptStudy_ctl06_aButton,#ctl00_ContentPlaceHolder1_rptStudy_ctl08_aButton,#ctl00_ContentPlaceHolder1_rptStudy_ctl10_aButton,#ctl00_ContentPlaceHolder1_rptStudy_ctl12_aButton,#ctl00_ContentPlaceHolder1_rptStudy_ctl14_aButton,#ctl00_ContentPlaceHolder1_rptStudy_ctl16_aButton,#ctl00_ContentPlaceHolder1_rptStudy_ctl18_aButton,#ctl00_ContentPlaceHolder1_rptStudy_ctl20_aButton,#ctl00_ContentPlaceHolder1_rptStudy_ctl22_aButton,#ctl00_ContentPlaceHolder1_rptStudy_ctl24_aButton,#ctl00_ContentPlaceHolder1_rptStudy_ctl26_aButton'

# print(csslist.split(','))
# print(csslist2.split(','))
#
# csslist = csslist2
# print(csslist.split(','))